### ISSUE TITLE
Create a Post

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-62/rare-v1-server-second-breakfast#10]
Given a user selects the "New Post" link in the navbar and are directed to the new post form
When they fill out the form correctly and submit
Then the post should be added and approved
And they should be directed to that post's detail page

**Comment by erniefabian3rd** [comment]
User can fill out a form to create a new post in both the main feed and "All Posts" page. Upon submission, the user is routed to the full detail view of the post they just created.
