### ISSUE TITLE
Delete a Post

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-62/rare-v1-server-second-breakfast#13]
Given the logged in user is on the `/my-posts` page
When they select a post's delete button
Then they should see an alert that reads: "Are you sure you want to delete this post?"
And if they click ok
Then the post should be deleted
And the post list should update

**Comment by erniefabian3rd** [comment]
Posts can now be deleted from home page, post details, and my-posts. Before deleting, user must confirm they want to delete the post in a popup window.
