### ISSUE TITLE
Add a comment to a post

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-62/rare-v1-server-second-breakfast#22]
Given a user is viewing the post details or a post's comments
When they click the "Add Comment" button
Then they should be routed to a comment form
And once the form is submitted
Then they should be routed to the comment page for that post

**Comment by jwhyteBNA** [comment]
Serve side complete

**Comment by erniefabian3rd** [comment]
User may now submit new comments and immediately see them in the comment list for that post.
